api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/config/api_platform']
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
    formats:
        json:
            mime_types: ['application/json']
        jsonapi:
            mime_types: ['application/vnd.api+json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
